services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 
      - PGHOST=db
      - PGUSER=postgres
      - PGPASS=rails@123
      - PG__DB=messenger_docker
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=rails@123
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    environment:
      - REDIS_URL=redis://redis:6379/1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle: